name: config

services:
  # The Django Web Server
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    # Runs migrations and starts Gunicorn
    command: >
      sh -c "python manage.py migrate && 
             python manage.py collectstatic --noinput && 
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  # The Celery Worker for Emails
  worker:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis

  # Internal Redis for the queue
  redis:
    image: redis:alpine