services:
  # The Django Web App
  - type: web
    name: taskflow-web
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false # We will paste the Aiven link in the dashboard
      - key: REDIS_URL
        sync: false
      - key: CELERY_BACKEND
        sync: false
      - key: REDIS_URL
        sync: false

  # The Celery Worker
  - type: worker
    name: taskflow-worker
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A config worker --loglevel=info --pool=solo"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CELERY_BROKER # Add this
        sync: false
      - key: CELERY_BACKEND # Add this
        sync: false
      - key: REDIS_URL # This is what your CACHES setting uses
        sync: false

  # Redis for Celery
  - type: redis
    name: taskflow-redis
    plan: free
    ipAllowList: [] # Allow internal access